data: 
  data_dir: data/humpback-whale-identification

train:
  data: 
    data_dir: data/humpback-whale-identification

  net:
    backbone_name: mobilenetv2_035
    pretrained: false
    embedding_size: 64
    num_classes: 4604

  loss:
    num_classes: 4604
    embedding_size: 64
    margin: 16
    scale: 32

  n_epochs: 2
  exp_dir: runs/
  seed: 42
  head_lr: 0.001
  backbone_lr: 0.0001
  batch_size: 64
  device: cpu

infer: 
  dataset_dir: data/humpback-whale-identification
  checkpoint_path: runs/best.ckpt
  device: cpu
  batch_size: 1
  threshold: 0.5
