version: '3.8'

services:
  test:
    build: .
    image: pythondestroyer/simple_ml_project_with_kafka:main
    command: pytest --skip-slow # remove skip-slow if want to test training phase too
    volumes: 
      - ./data/:/app/data
      - ./runs:/app/runs
    environment:
      - ANSIBLE_PASSWD=${ANSIBLE_PASSWD}
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

  zookeeper:
      image: confluentinc/cp-zookeeper:7.3.2
      container_name: zookeeper
      environment:
          ZOOKEEPER_CLIENT_PORT: 2181     
   
  kafka:
      image: confluentinc/cp-kafka:7.3.2
      container_name: kafka
      ports:
          - "${KAFKA_PORT}:${KAFKA_PORT}"
      depends_on:
          - zookeeper
      environment:
          KAFKA_HOST: ${KAFKA_HOST}
          KAFKA_PORT: ${KAFKA_PORT}
          KAFKA_BROKER_ID: 1
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
          KAFKA_LISTENERS: INTERNAL://:${KAFKA_PORT}
          KAFKA_ADVERTISED_LISTENERS: INTERNAL://${KAFKA_HOST}:${KAFKA_PORT}
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT

  kafka-topics-generator:
      image: confluentinc/cp-kafka:7.3.2
      container_name: kafka-topics-generator
      depends_on:
          - kafka
      command: >
          bash -c
            "sleep 5s &&
            kafka-topics --create --topic=kafka-predictions --if-not-exists --bootstrap-server=${KAFKA_HOST}:${KAFKA_PORT}"
  
  kafka-consumer:
      image: confluentinc/cp-kafka:7.3.2
      container_name: kafka-consumer
      command: >
          bash -c
            "kafka-console-consumer --bootstrap-server ${KAFKA_HOST}:${KAFKA_PORT} --topic kafka-pred --from-beginning"
