name: CD pipeline

on:
  workflow_run:
    workflows: [CI pipeline]
    types:
      - completed

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/simple_ml_project_with_kafka # ${{ github.repository }}


jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set env vars
        run: |
          touch .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo ANSIBLE_PASSWD=${{ secrets.ANSIBLE_PASSWD }} >> .env
          echo KAFKA_HOST=${{ secrets.KAFKA_HOST }} >> .env
          echo KAFKA_PORT=${{ secrets.KAFKA_PORT }} >> .env
      
      - name: Pull with Docker Compose
        run: docker compose pull
      
      - name: Run tests
        run: timeout 30 sh -c 'docker compose up --abort-on-container-exit'
